CREATE PROCEDURE `sp_Conf_Values`(in COD_CLI varchar(10), in COD_EMP varchar(10), in pMES varchar(20), in pANO varchar(10), in OFFS int)
BEGIN
select A.ESPECIE, A.NRO_DOCUMENTO as NUMERO, A.CHAVE_ACESSO as `CHAVE ACESSO`, A.TOTAL_NFE as `VALOR TOTAL`, A.BASE_ICMS as `BASE ICMS`, A.VALOR_ICMS as `VALOR ICMS`, A.BASE_ICMS_ST as `BASE ICMS/ST`, A.VALOR_ICMS_ST as `VALOR ICMS/ST`, B.VALOR_TOTAL_NFE as `VALOR TOTAL NDD`, B.BASE_ICMS as `BASE ICMS NDD`, B.VALOR_ICMS as `VALOR ICMS NDD`, B.BASE_ICMS_ST as `BASE ICMS/ST NDD`, B.VALOR_ICMS_ST as `VALOR ICMS/ST NDD` 
from
(select COD_CLIENTE, COD_EMPRESA, MES, ANO, CHAVE_ACESSO, DTA_ENT_SAIDA, ESPECIE, CGO, NRO_DOCUMENTO, round(sum(VALOR_CONTABIL), 2) as TOTAL_NFE, round(sum(BASE_ICMS), 2) as BASE_ICMS, round(sum(VALOR_ICMS), 2) as VALOR_ICMS, round(sum(BASE_ICMS_ST), 2) as BASE_ICMS_ST, round(sum(VALOR_ICMS_ST), 2) as VALOR_ICMS_ST, round(sum(VALOR_OUTRAS_ICMS), 2) as VALOR_OUTRAS_ICMS
  from db_sis.tb_conf_c5
  where COD_CLIENTE = COD_CLI AND COD_EMPRESA = COD_EMP AND MES = pMES AND ANO = pANO
  group by COD_CLIENTE, COD_EMPRESA, MES, ANO, CHAVE_ACESSO, DTA_ENT_SAIDA, ESPECIE, CGO, NRO_DOCUMENTO
  order by NRO_DOCUMENTO) A
  left join
  (select COD_CLIENTE, COD_EMPRESA, MES, ANO, CHAVE_ACESSO, DTA_EMISSAO, NUMERO_DA_NOTA, VALOR_TOTAL_NFE, BASE_ICMS,
  VALOR_ICMS, BASE_ICMS_ST, VALOR_ICMS_ST from db_sis.tb_conf_ndd
  where COD_CLIENTE = COD_CLI AND COD_EMPRESA = COD_EMP AND MES = pMES AND ANO = pANO order by NUMERO_DA_NOTA) B
   on A.CHAVE_ACESSO = B.CHAVE_ACESSO
   where A.COD_CLIENTE = B.COD_CLIENTE and A.COD_EMPRESA = B.COD_EMPRESA and A.MES = B.MES and A.ANO = B.ANO 
   and(A.TOTAL_NFE <> B.VALOR_TOTAL_NFE or A.BASE_ICMS <> B.BASE_ICMS or A.VALOR_ICMS <> B.VALOR_ICMS or A.BASE_ICMS_ST <> B.BASE_ICMS_ST or A.VALOR_ICMS_ST <> B.VALOR_ICMS_ST)
   and A.COD_CLIENTE = COD_CLI AND A.COD_EMPRESA = COD_EMP AND A.MES = pMES AND A.ANO = pANO order by A.NRO_DOCUMENTO
   LIMIT 26 OFFSET OFFS;

END